# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sandbox.v1 import sandbox_pb2 as sandbox_dot_v1_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox/v1/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/sandbox.v1.SandboxService/CreateSession',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/sandbox.v1.SandboxService/DestroySession',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.DestroySessionRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.DestroySessionResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/sandbox.v1.SandboxService/Exec',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ExecStream = channel.unary_stream(
                '/sandbox.v1.SandboxService/ExecStream',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/sandbox.v1.SandboxService/WriteFile',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/sandbox.v1.SandboxService/ReadFile',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/sandbox.v1.SandboxService/ListFiles',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.PipInstall = channel.unary_unary(
                '/sandbox.v1.SandboxService/PipInstall',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.PipInstallRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.PipInstallResponse.FromString,
                _registered_method=True)
        self.RunSubAgent = channel.unary_unary(
                '/sandbox.v1.SandboxService/RunSubAgent',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.RunSubAgentRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.RunSubAgentResponse.FromString,
                _registered_method=True)
        self.ConfirmAction = channel.unary_unary(
                '/sandbox.v1.SandboxService/ConfirmAction',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ConfirmActionRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ConfirmActionResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PipInstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSubAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.CreateSessionRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.CreateSessionResponse.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.DestroySessionRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.DestroySessionResponse.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.SerializeToString,
            ),
            'ExecStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecStream,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ListFilesRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ListFilesResponse.SerializeToString,
            ),
            'PipInstall': grpc.unary_unary_rpc_method_handler(
                    servicer.PipInstall,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.PipInstallRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.PipInstallResponse.SerializeToString,
            ),
            'RunSubAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSubAgent,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.RunSubAgentRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.RunSubAgentResponse.SerializeToString,
            ),
            'ConfirmAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmAction,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ConfirmActionRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ConfirmActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/CreateSession',
            sandbox_dot_v1_dot_sandbox__pb2.CreateSessionRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/DestroySession',
            sandbox_dot_v1_dot_sandbox__pb2.DestroySessionRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.DestroySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/Exec',
            sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sandbox.v1.SandboxService/ExecStream',
            sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/WriteFile',
            sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/ReadFile',
            sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/ListFiles',
            sandbox_dot_v1_dot_sandbox__pb2.ListFilesRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PipInstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/PipInstall',
            sandbox_dot_v1_dot_sandbox__pb2.PipInstallRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.PipInstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSubAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/RunSubAgent',
            sandbox_dot_v1_dot_sandbox__pb2.RunSubAgentRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.RunSubAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/ConfirmAction',
            sandbox_dot_v1_dot_sandbox__pb2.ConfirmActionRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ConfirmActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
