#!/bin/bash
set -e -x

cd $(dirname $0)/..

. ./hack/version.sh

RUNC_VERSION=v1.0.0
CHARTS_DIR=build/static/charts
RUNC_DIR=build/src/github.com/opencontainers/runc
DATA_DIR=build/data

umask 022
rm -rf ${CHARTS_DIR}
rm -rf ${RUNC_DIR}
mkdir -p ${CHARTS_DIR}
mkdir -p ${DATA_DIR}
mkdir -p bin

git clone --depth=1 https://github.com/opencontainers/runc ${RUNC_DIR} || true
pushd ${RUNC_DIR}
git fetch --all --tags
git checkout ${RUNC_VERSION} -b k8e
popd

#nerdctl for containerd , v0.11.0
echo "download nerdctl..."
if [ ${ARCH} = amd64 ]; then
  curl --compressed -sfL https://github.com/containerd/nerdctl/releases/download/v0.11.0/nerdctl-0.11.0-linux-amd64.tar.gz | tar zxf - -C bin
elif [ ${ARCH} = aarch64 ] || [ ${ARCH} = arm64 ]; then
  curl --compressed -sfL https://github.com/containerd/nerdctl/releases/download/v0.11.0/nerdctl-0.11.0-linux-arm64.tar.gz | tar zxf - -C bin
fi

# calicoctl
echo "download calicoctl..."
if [ ${ARCH} = amd64 ]; then
  curl -o bin/calicoctl -O -L  "https://github.com/projectcalico/calicoctl/releases/download/v3.20.0/calicoctl"
elif [ ${ARCH} = aarch64 ] || [ ${ARCH} = arm64 ]; then
  curl -o bin/calicoctl -O -L  "https://github.com/projectcalico/calicoctl/releases/download/v3.20.0/calicoctl-linux-arm64"
fi
chmod +x bin/calicoctl