// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sandbox/v1/sandbox.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretRef references a key in a same-namespace K8s Secret. Values are resolved
// at exec time only and never stored on the SandboxSession CRD (#505 / KIP-12 B).
type SecretRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"` // K8s Secret name
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                 // key within Secret.data
	EnvVar        string                 `protobuf:"bytes,3,opt,name=env_var,json=envVar,proto3" json:"env_var,omitempty"`             // environment variable name injected into the process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRef) Reset() {
	*x = SecretRef{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRef) ProtoMessage() {}

func (x *SecretRef) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRef.ProtoReflect.Descriptor instead.
func (*SecretRef) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *SecretRef) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretRef) GetEnvVar() string {
	if x != nil {
		return x.EnvVar
	}
	return ""
}

type CreateSessionRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SessionId    string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId     string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AllowedHosts []string               `protobuf:"bytes,3,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	RuntimeClass string                 `protobuf:"bytes,4,opt,name=runtime_class,json=runtimeClass,proto3" json:"runtime_class,omitempty"`
	// Non-sensitive environment variables persisted on the SandboxSession and
	// applied at exec time so warm-pool pods stay reusable (KIP-12 Part B / #483).
	Env           map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SecretRefs    []*SecretRef      `protobuf:"bytes,6,rep,name=secret_refs,json=secretRefs,proto3" json:"secret_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateSessionRequest) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *CreateSessionRequest) GetRuntimeClass() string {
	if x != nil {
		return x.RuntimeClass
	}
	return ""
}

func (x *CreateSessionRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateSessionRequest) GetSecretRefs() []*SecretRef {
	if x != nil {
		return x.SecretRefs
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PodIp         string                 `protobuf:"bytes,2,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Phase          string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	RuntimeClass   string                 `protobuf:"bytes,3,opt,name=runtime_class,json=runtimeClass,proto3" json:"runtime_class,omitempty"`
	PodIp          string                 `protobuf:"bytes,4,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	TenantId       string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                // unix seconds; 0 if none
	EnvKeys        []string               `protobuf:"bytes,7,rep,name=env_keys,json=envKeys,proto3" json:"env_keys,omitempty"`                       // keys only, never values
	SecretEnvVars  []string               `protobuf:"bytes,8,rep,name=secret_env_vars,json=secretEnvVars,proto3" json:"secret_env_vars,omitempty"`   // env_var names from secret_refs only
	BackgroundRuns int32                  `protobuf:"varint,9,opt,name=background_runs,json=backgroundRuns,proto3" json:"background_runs,omitempty"` // active entries known to gateway registry
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *GetSessionResponse) GetRuntimeClass() string {
	if x != nil {
		return x.RuntimeClass
	}
	return ""
}

func (x *GetSessionResponse) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *GetSessionResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetSessionResponse) GetEnvKeys() []string {
	if x != nil {
		return x.EnvKeys
	}
	return nil
}

func (x *GetSessionResponse) GetSecretEnvVars() []string {
	if x != nil {
		return x.SecretEnvVars
	}
	return nil
}

func (x *GetSessionResponse) GetBackgroundRuns() int32 {
	if x != nil {
		return x.BackgroundRuns
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"` // empty = Active only; "all" = every phase
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*GetSessionResponse  `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*GetSessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *DestroySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionResponse) Reset() {
	*x = DestroySessionResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionResponse) ProtoMessage() {}

func (x *DestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionResponse.ProtoReflect.Descriptor instead.
func (*DestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *DestroySessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Workdir       string                 `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Background    bool                   `protobuf:"varint,5,opt,name=background,proto3" json:"background,omitempty"` // submit asynchronously, return run_id immediately
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`      // optional hint: python|bash|node|ts (observability)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ExecRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

func (x *ExecRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ExecResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Stdout    string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr    string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode  int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	SessionId string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId     string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // set when background=true
	// started|running|completed|timed_out|failed
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DurationMs    int64  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // wall-clock ms for this execution (0 if unknown/started)
	Truncated     bool   `protobuf:"varint,8,opt,name=truncated,proto3" json:"truncated,omitempty"`                     // stdout and/or stderr hit size cap
	Language      string `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`                        // echoed from request when set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ExecResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ExecStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamResponse) Reset() {
	*x = ExecStreamResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamResponse) ProtoMessage() {}

func (x *ExecStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamResponse.ProtoReflect.Descriptor instead.
func (*ExecStreamResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *ExecStreamResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *WriteFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WriteFileRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *WriteFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *ReadFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *ReadFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListFilesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Return only files modified after this unix timestamp (0 = all).
	Since         int64 `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *ListFilesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListFilesRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileEntry           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{17}
}

func (x *ListFilesResponse) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Modified      int64                  `protobuf:"varint,2,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetModified() int64 {
	if x != nil {
		return x.Modified
	}
	return 0
}

type PipInstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Packages      []string               `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipInstallRequest) Reset() {
	*x = PipInstallRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipInstallRequest) ProtoMessage() {}

func (x *PipInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipInstallRequest.ProtoReflect.Descriptor instead.
func (*PipInstallRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *PipInstallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PipInstallRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type PipInstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipInstallResponse) Reset() {
	*x = PipInstallResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipInstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipInstallResponse) ProtoMessage() {}

func (x *PipInstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipInstallResponse.ProtoReflect.Descriptor instead.
func (*PipInstallResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *PipInstallResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *PipInstallResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type RunSubAgentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentSessionId string                 `protobuf:"bytes,1,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	AgentType       string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	WorkspacePath   string                 `protobuf:"bytes,3,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunSubAgentRequest) Reset() {
	*x = RunSubAgentRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSubAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSubAgentRequest) ProtoMessage() {}

func (x *RunSubAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSubAgentRequest.ProtoReflect.Descriptor instead.
func (*RunSubAgentRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{21}
}

func (x *RunSubAgentRequest) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *RunSubAgentRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *RunSubAgentRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

type RunSubAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSubAgentResponse) Reset() {
	*x = RunSubAgentResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSubAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSubAgentResponse) ProtoMessage() {}

func (x *RunSubAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSubAgentResponse.ProtoReflect.Descriptor instead.
func (*RunSubAgentResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{22}
}

func (x *RunSubAgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ConfirmActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ApprovalId    string                 `protobuf:"bytes,3,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmActionRequest) Reset() {
	*x = ConfirmActionRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmActionRequest) ProtoMessage() {}

func (x *ConfirmActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmActionRequest.ProtoReflect.Descriptor instead.
func (*ConfirmActionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{23}
}

func (x *ConfirmActionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConfirmActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConfirmActionRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

type ConfirmActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmActionResponse) Reset() {
	*x = ConfirmActionResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmActionResponse) ProtoMessage() {}

func (x *ConfirmActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmActionResponse.ProtoReflect.Descriptor instead.
func (*ConfirmActionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{24}
}

func (x *ConfirmActionResponse) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ConfirmActionResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ApproveActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveActionRequest) Reset() {
	*x = ApproveActionRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveActionRequest) ProtoMessage() {}

func (x *ApproveActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveActionRequest.ProtoReflect.Descriptor instead.
func (*ApproveActionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{25}
}

func (x *ApproveActionRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApproveActionRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApproveActionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApproveActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveActionResponse) Reset() {
	*x = ApproveActionResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveActionResponse) ProtoMessage() {}

func (x *ApproveActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveActionResponse.ProtoReflect.Descriptor instead.
func (*ApproveActionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{26}
}

func (x *ApproveActionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csr           string                 `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`                                          // PEM-encoded PKCS#10 certificate signing request
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`          // e.g. hostname, for audit logging
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // k8e version, for audit logging
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{27}
}

func (x *LoginRequest) GetCsr() string {
	if x != nil {
		return x.Csr
	}
	return ""
}

func (x *LoginRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *LoginRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          string                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`                             // PEM-encoded signed client certificate
	CaCert        string                 `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`           // PEM-encoded sandbox CA certificate (trust anchor)
	ValidDays     int64                  `protobuf:"varint,3,opt,name=valid_days,json=validDays,proto3" json:"valid_days,omitempty"` // days the certificate is valid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{28}
}

func (x *LoginResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *LoginResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *LoginResponse) GetValidDays() int64 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

type PollRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRunRequest) Reset() {
	*x = PollRunRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRunRequest) ProtoMessage() {}

func (x *PollRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRunRequest.ProtoReflect.Descriptor instead.
func (*PollRunRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{29}
}

func (x *PollRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type PollRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// started|running|completed|failed|timed_out|not_found
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Stdout        string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	DurationMs    int64  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Truncated     bool   `protobuf:"varint,7,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRunResponse) Reset() {
	*x = PollRunResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRunResponse) ProtoMessage() {}

func (x *PollRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRunResponse.ProtoReflect.Descriptor instead.
func (*PollRunResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{30}
}

func (x *PollRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PollRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PollRunResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *PollRunResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *PollRunResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *PollRunResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PollRunResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// GetTranscriptRequest reads a file-backed exec transcript window.
type GetTranscriptRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Byte offset to start reading from. 0 = start of transcript.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Max bytes to return in this window. 0 = server default (64 KiB).
	Limit         int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptRequest) Reset() {
	*x = GetTranscriptRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptRequest) ProtoMessage() {}

func (x *GetTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptRequest.ProtoReflect.Descriptor instead.
func (*GetTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{31}
}

func (x *GetTranscriptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetTranscriptRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTranscriptRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTranscriptResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Output          string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`                                           // window content, line-aligned
	Offset          int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                          // absolute offset this window starts at
	NextOffset      int64                  `protobuf:"varint,4,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`                // offset for the next window; == file size at EOF
	TruncatedBefore bool                   `protobuf:"varint,5,opt,name=truncated_before,json=truncatedBefore,proto3" json:"truncated_before,omitempty"` // true when the window starts mid-file (lines were skipped)
	Eof             bool                   `protobuf:"varint,6,opt,name=eof,proto3" json:"eof,omitempty"`                                                // true when next_offset reached the end of the transcript
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTranscriptResponse) Reset() {
	*x = GetTranscriptResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptResponse) ProtoMessage() {}

func (x *GetTranscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptResponse.ProtoReflect.Descriptor instead.
func (*GetTranscriptResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{32}
}

func (x *GetTranscriptResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetTranscriptResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GetTranscriptResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTranscriptResponse) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *GetTranscriptResponse) GetTruncatedBefore() bool {
	if x != nil {
		return x.TruncatedBefore
	}
	return false
}

func (x *GetTranscriptResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// GetEventsRequest reads the daemon NDJSON event stream (KIP-16 M5).
type GetEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty = all events (daemon-wide). When set, only events for this session.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Max events to return in this call (0 = server default 500).
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{33}
}

func (x *GetEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetEventsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []string               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`        // raw NDJSON lines
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"` // more events exist beyond the returned window
	Returned      int64                  `protobuf:"varint,3,opt,name=returned,proto3" json:"returned,omitempty"`   // number of lines returned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{34}
}

func (x *GetEventsResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *GetEventsResponse) GetReturned() int64 {
	if x != nil {
		return x.Returned
	}
	return 0
}

var File_sandbox_v1_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x18sandbox/v1/sandbox.proto\x12\n" +
	"sandbox.v1\"W\n" +
	"\tSecretRef\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x17\n" +
	"\aenv_var\x18\x03 \x01(\tR\x06envVar\"\xc9\x02\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12#\n" +
	"\rallowed_hosts\x18\x03 \x03(\tR\fallowedHosts\x12#\n" +
	"\rruntime_class\x18\x04 \x01(\tR\fruntimeClass\x12;\n" +
	"\x03env\x18\x05 \x03(\v2).sandbox.v1.CreateSessionRequest.EnvEntryR\x03env\x126\n" +
	"\vsecret_refs\x18\x06 \x03(\v2\x15.sandbox.v1.SecretRefR\n" +
	"secretRefs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06pod_ip\x18\x02 \x01(\tR\x05podIp\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xad\x02\n" +
	"\x12GetSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rruntime_class\x18\x03 \x01(\tR\fruntimeClass\x12\x15\n" +
	"\x06pod_ip\x18\x04 \x01(\tR\x05podIp\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x19\n" +
	"\benv_keys\x18\a \x03(\tR\aenvKeys\x12&\n" +
	"\x0fsecret_env_vars\x18\b \x03(\tR\rsecretEnvVars\x12'\n" +
	"\x0fbackground_runs\x18\t \x01(\x05R\x0ebackgroundRuns\"+\n" +
	"\x13ListSessionsRequest\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\"R\n" +
	"\x14ListSessionsResponse\x12:\n" +
	"\bsessions\x18\x01 \x03(\v2\x1e.sandbox.v1.GetSessionResponseR\bsessions\"6\n" +
	"\x15DestroySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"(\n" +
	"\x16DestroySessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xb6\x01\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x12\x1e\n" +
	"\n" +
	"background\x18\x05 \x01(\bR\n" +
	"background\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\"\x84\x02\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttruncated\x18\b \x01(\bR\ttruncated\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\"*\n" +
	"\x12ExecStreamResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\"s\n" +
	"\x10WriteFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"#\n" +
	"\x11WriteFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"D\n" +
	"\x0fReadFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"G\n" +
	"\x10ListFilesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x03R\x05since\"@\n" +
	"\x11ListFilesResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.sandbox.v1.FileEntryR\x05files\";\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bmodified\x18\x02 \x01(\x03R\bmodified\"N\n" +
	"\x11PipInstallRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bpackages\x18\x02 \x03(\tR\bpackages\"I\n" +
	"\x12PipInstallResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"\x86\x01\n" +
	"\x12RunSubAgentRequest\x12*\n" +
	"\x11parent_session_id\x18\x01 \x01(\tR\x0fparentSessionId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12%\n" +
	"\x0eworkspace_path\x18\x03 \x01(\tR\rworkspacePath\"4\n" +
	"\x13RunSubAgentResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"n\n" +
	"\x14ConfirmActionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vapproval_id\x18\x03 \x01(\tR\n" +
	"approvalId\"T\n" +
	"\x15ConfirmActionResponse\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"k\n" +
	"\x14ApproveActionRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"'\n" +
	"\x15ApproveActionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"h\n" +
	"\fLoginRequest\x12\x10\n" +
	"\x03csr\x18\x01 \x01(\tR\x03csr\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\"[\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\tR\x04cert\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\tR\x06caCert\x12\x1d\n" +
	"\n" +
	"valid_days\x18\x03 \x01(\x03R\tvalidDays\"'\n" +
	"\x0ePollRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xcc\x01\n" +
	"\x0fPollRunResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttruncated\x18\a \x01(\bR\ttruncated\"c\n" +
	"\x14GetTranscriptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\xc4\x01\n" +
	"\x15GetTranscriptResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1f\n" +
	"\vnext_offset\x18\x04 \x01(\x03R\n" +
	"nextOffset\x12)\n" +
	"\x10truncated_before\x18\x05 \x01(\bR\x0ftruncatedBefore\x12\x10\n" +
	"\x03eof\x18\x06 \x01(\bR\x03eof\"G\n" +
	"\x10GetEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"e\n" +
	"\x11GetEventsResponse\x12\x16\n" +
	"\x06events\x18\x01 \x03(\tR\x06events\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\x12\x1a\n" +
	"\breturned\x18\x03 \x01(\x03R\breturned2\xa9\n" +
	"\n" +
	"\x0eSandboxService\x12T\n" +
	"\rCreateSession\x12 .sandbox.v1.CreateSessionRequest\x1a!.sandbox.v1.CreateSessionResponse\x12K\n" +
	"\n" +
	"GetSession\x12\x1d.sandbox.v1.GetSessionRequest\x1a\x1e.sandbox.v1.GetSessionResponse\x12Q\n" +
	"\fListSessions\x12\x1f.sandbox.v1.ListSessionsRequest\x1a .sandbox.v1.ListSessionsResponse\x12W\n" +
	"\x0eDestroySession\x12!.sandbox.v1.DestroySessionRequest\x1a\".sandbox.v1.DestroySessionResponse\x129\n" +
	"\x04Exec\x12\x17.sandbox.v1.ExecRequest\x1a\x18.sandbox.v1.ExecResponse\x12G\n" +
	"\n" +
	"ExecStream\x12\x17.sandbox.v1.ExecRequest\x1a\x1e.sandbox.v1.ExecStreamResponse0\x01\x12H\n" +
	"\tWriteFile\x12\x1c.sandbox.v1.WriteFileRequest\x1a\x1d.sandbox.v1.WriteFileResponse\x12E\n" +
	"\bReadFile\x12\x1b.sandbox.v1.ReadFileRequest\x1a\x1c.sandbox.v1.ReadFileResponse\x12H\n" +
	"\tListFiles\x12\x1c.sandbox.v1.ListFilesRequest\x1a\x1d.sandbox.v1.ListFilesResponse\x12K\n" +
	"\n" +
	"PipInstall\x12\x1d.sandbox.v1.PipInstallRequest\x1a\x1e.sandbox.v1.PipInstallResponse\x12N\n" +
	"\vRunSubAgent\x12\x1e.sandbox.v1.RunSubAgentRequest\x1a\x1f.sandbox.v1.RunSubAgentResponse\x12T\n" +
	"\rConfirmAction\x12 .sandbox.v1.ConfirmActionRequest\x1a!.sandbox.v1.ConfirmActionResponse\x12T\n" +
	"\rApproveAction\x12 .sandbox.v1.ApproveActionRequest\x1a!.sandbox.v1.ApproveActionResponse\x12<\n" +
	"\x05Login\x12\x18.sandbox.v1.LoginRequest\x1a\x19.sandbox.v1.LoginResponse\x12B\n" +
	"\aPollRun\x12\x1a.sandbox.v1.PollRunRequest\x1a\x1b.sandbox.v1.PollRunResponse\x12T\n" +
	"\rGetTranscript\x12 .sandbox.v1.GetTranscriptRequest\x1a!.sandbox.v1.GetTranscriptResponse\x12H\n" +
	"\tGetEvents\x12\x1c.sandbox.v1.GetEventsRequest\x1a\x1d.sandbox.v1.GetEventsResponseB?Z=github.com/xiaods/k8e/pkg/sandboxmatrix/grpc/pb/sandbox/v1;pbb\x06proto3"

var (
	file_sandbox_v1_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_v1_sandbox_proto_rawDescData []byte
)

func file_sandbox_v1_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)))
	})
	return file_sandbox_v1_sandbox_proto_rawDescData
}

var file_sandbox_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_sandbox_v1_sandbox_proto_goTypes = []any{
	(*SecretRef)(nil),              // 0: sandbox.v1.SecretRef
	(*CreateSessionRequest)(nil),   // 1: sandbox.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 2: sandbox.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),      // 3: sandbox.v1.GetSessionRequest
	(*GetSessionResponse)(nil),     // 4: sandbox.v1.GetSessionResponse
	(*ListSessionsRequest)(nil),    // 5: sandbox.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 6: sandbox.v1.ListSessionsResponse
	(*DestroySessionRequest)(nil),  // 7: sandbox.v1.DestroySessionRequest
	(*DestroySessionResponse)(nil), // 8: sandbox.v1.DestroySessionResponse
	(*ExecRequest)(nil),            // 9: sandbox.v1.ExecRequest
	(*ExecResponse)(nil),           // 10: sandbox.v1.ExecResponse
	(*ExecStreamResponse)(nil),     // 11: sandbox.v1.ExecStreamResponse
	(*WriteFileRequest)(nil),       // 12: sandbox.v1.WriteFileRequest
	(*WriteFileResponse)(nil),      // 13: sandbox.v1.WriteFileResponse
	(*ReadFileRequest)(nil),        // 14: sandbox.v1.ReadFileRequest
	(*ReadFileResponse)(nil),       // 15: sandbox.v1.ReadFileResponse
	(*ListFilesRequest)(nil),       // 16: sandbox.v1.ListFilesRequest
	(*ListFilesResponse)(nil),      // 17: sandbox.v1.ListFilesResponse
	(*FileEntry)(nil),              // 18: sandbox.v1.FileEntry
	(*PipInstallRequest)(nil),      // 19: sandbox.v1.PipInstallRequest
	(*PipInstallResponse)(nil),     // 20: sandbox.v1.PipInstallResponse
	(*RunSubAgentRequest)(nil),     // 21: sandbox.v1.RunSubAgentRequest
	(*RunSubAgentResponse)(nil),    // 22: sandbox.v1.RunSubAgentResponse
	(*ConfirmActionRequest)(nil),   // 23: sandbox.v1.ConfirmActionRequest
	(*ConfirmActionResponse)(nil),  // 24: sandbox.v1.ConfirmActionResponse
	(*ApproveActionRequest)(nil),   // 25: sandbox.v1.ApproveActionRequest
	(*ApproveActionResponse)(nil),  // 26: sandbox.v1.ApproveActionResponse
	(*LoginRequest)(nil),           // 27: sandbox.v1.LoginRequest
	(*LoginResponse)(nil),          // 28: sandbox.v1.LoginResponse
	(*PollRunRequest)(nil),         // 29: sandbox.v1.PollRunRequest
	(*PollRunResponse)(nil),        // 30: sandbox.v1.PollRunResponse
	(*GetTranscriptRequest)(nil),   // 31: sandbox.v1.GetTranscriptRequest
	(*GetTranscriptResponse)(nil),  // 32: sandbox.v1.GetTranscriptResponse
	(*GetEventsRequest)(nil),       // 33: sandbox.v1.GetEventsRequest
	(*GetEventsResponse)(nil),      // 34: sandbox.v1.GetEventsResponse
	nil,                            // 35: sandbox.v1.CreateSessionRequest.EnvEntry
}
var file_sandbox_v1_sandbox_proto_depIdxs = []int32{
	35, // 0: sandbox.v1.CreateSessionRequest.env:type_name -> sandbox.v1.CreateSessionRequest.EnvEntry
	0,  // 1: sandbox.v1.CreateSessionRequest.secret_refs:type_name -> sandbox.v1.SecretRef
	4,  // 2: sandbox.v1.ListSessionsResponse.sessions:type_name -> sandbox.v1.GetSessionResponse
	18, // 3: sandbox.v1.ListFilesResponse.files:type_name -> sandbox.v1.FileEntry
	1,  // 4: sandbox.v1.SandboxService.CreateSession:input_type -> sandbox.v1.CreateSessionRequest
	3,  // 5: sandbox.v1.SandboxService.GetSession:input_type -> sandbox.v1.GetSessionRequest
	5,  // 6: sandbox.v1.SandboxService.ListSessions:input_type -> sandbox.v1.ListSessionsRequest
	7,  // 7: sandbox.v1.SandboxService.DestroySession:input_type -> sandbox.v1.DestroySessionRequest
	9,  // 8: sandbox.v1.SandboxService.Exec:input_type -> sandbox.v1.ExecRequest
	9,  // 9: sandbox.v1.SandboxService.ExecStream:input_type -> sandbox.v1.ExecRequest
	12, // 10: sandbox.v1.SandboxService.WriteFile:input_type -> sandbox.v1.WriteFileRequest
	14, // 11: sandbox.v1.SandboxService.ReadFile:input_type -> sandbox.v1.ReadFileRequest
	16, // 12: sandbox.v1.SandboxService.ListFiles:input_type -> sandbox.v1.ListFilesRequest
	19, // 13: sandbox.v1.SandboxService.PipInstall:input_type -> sandbox.v1.PipInstallRequest
	21, // 14: sandbox.v1.SandboxService.RunSubAgent:input_type -> sandbox.v1.RunSubAgentRequest
	23, // 15: sandbox.v1.SandboxService.ConfirmAction:input_type -> sandbox.v1.ConfirmActionRequest
	25, // 16: sandbox.v1.SandboxService.ApproveAction:input_type -> sandbox.v1.ApproveActionRequest
	27, // 17: sandbox.v1.SandboxService.Login:input_type -> sandbox.v1.LoginRequest
	29, // 18: sandbox.v1.SandboxService.PollRun:input_type -> sandbox.v1.PollRunRequest
	31, // 19: sandbox.v1.SandboxService.GetTranscript:input_type -> sandbox.v1.GetTranscriptRequest
	33, // 20: sandbox.v1.SandboxService.GetEvents:input_type -> sandbox.v1.GetEventsRequest
	2,  // 21: sandbox.v1.SandboxService.CreateSession:output_type -> sandbox.v1.CreateSessionResponse
	4,  // 22: sandbox.v1.SandboxService.GetSession:output_type -> sandbox.v1.GetSessionResponse
	6,  // 23: sandbox.v1.SandboxService.ListSessions:output_type -> sandbox.v1.ListSessionsResponse
	8,  // 24: sandbox.v1.SandboxService.DestroySession:output_type -> sandbox.v1.DestroySessionResponse
	10, // 25: sandbox.v1.SandboxService.Exec:output_type -> sandbox.v1.ExecResponse
	11, // 26: sandbox.v1.SandboxService.ExecStream:output_type -> sandbox.v1.ExecStreamResponse
	13, // 27: sandbox.v1.SandboxService.WriteFile:output_type -> sandbox.v1.WriteFileResponse
	15, // 28: sandbox.v1.SandboxService.ReadFile:output_type -> sandbox.v1.ReadFileResponse
	17, // 29: sandbox.v1.SandboxService.ListFiles:output_type -> sandbox.v1.ListFilesResponse
	20, // 30: sandbox.v1.SandboxService.PipInstall:output_type -> sandbox.v1.PipInstallResponse
	22, // 31: sandbox.v1.SandboxService.RunSubAgent:output_type -> sandbox.v1.RunSubAgentResponse
	24, // 32: sandbox.v1.SandboxService.ConfirmAction:output_type -> sandbox.v1.ConfirmActionResponse
	26, // 33: sandbox.v1.SandboxService.ApproveAction:output_type -> sandbox.v1.ApproveActionResponse
	28, // 34: sandbox.v1.SandboxService.Login:output_type -> sandbox.v1.LoginResponse
	30, // 35: sandbox.v1.SandboxService.PollRun:output_type -> sandbox.v1.PollRunResponse
	32, // 36: sandbox.v1.SandboxService.GetTranscript:output_type -> sandbox.v1.GetTranscriptResponse
	34, // 37: sandbox.v1.SandboxService.GetEvents:output_type -> sandbox.v1.GetEventsResponse
	21, // [21:38] is the sub-list for method output_type
	4,  // [4:21] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sandbox_v1_sandbox_proto_init() }
func file_sandbox_v1_sandbox_proto_init() {
	if File_sandbox_v1_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_v1_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_v1_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_v1_sandbox_proto = out.File
	file_sandbox_v1_sandbox_proto_goTypes = nil
	file_sandbox_v1_sandbox_proto_depIdxs = nil
}
