// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/sandbox/v1/sandbox.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_CreateSession_FullMethodName      = "/sandbox.v1.SandboxService/CreateSession"
	SandboxService_GetSession_FullMethodName         = "/sandbox.v1.SandboxService/GetSession"
	SandboxService_ListSessions_FullMethodName       = "/sandbox.v1.SandboxService/ListSessions"
	SandboxService_DestroySession_FullMethodName     = "/sandbox.v1.SandboxService/DestroySession"
	SandboxService_PauseSession_FullMethodName       = "/sandbox.v1.SandboxService/PauseSession"
	SandboxService_ResumeSession_FullMethodName      = "/sandbox.v1.SandboxService/ResumeSession"
	SandboxService_Exec_FullMethodName               = "/sandbox.v1.SandboxService/Exec"
	SandboxService_ExecStream_FullMethodName         = "/sandbox.v1.SandboxService/ExecStream"
	SandboxService_WriteFile_FullMethodName          = "/sandbox.v1.SandboxService/WriteFile"
	SandboxService_ReadFile_FullMethodName           = "/sandbox.v1.SandboxService/ReadFile"
	SandboxService_ListFiles_FullMethodName          = "/sandbox.v1.SandboxService/ListFiles"
	SandboxService_PipInstall_FullMethodName         = "/sandbox.v1.SandboxService/PipInstall"
	SandboxService_RunSubAgent_FullMethodName        = "/sandbox.v1.SandboxService/RunSubAgent"
	SandboxService_ConfirmAction_FullMethodName      = "/sandbox.v1.SandboxService/ConfirmAction"
	SandboxService_ApproveAction_FullMethodName      = "/sandbox.v1.SandboxService/ApproveAction"
	SandboxService_Login_FullMethodName              = "/sandbox.v1.SandboxService/Login"
	SandboxService_PollRun_FullMethodName            = "/sandbox.v1.SandboxService/PollRun"
	SandboxService_GetTranscript_FullMethodName      = "/sandbox.v1.SandboxService/GetTranscript"
	SandboxService_GetEvents_FullMethodName          = "/sandbox.v1.SandboxService/GetEvents"
	SandboxService_SnapshotPut_FullMethodName        = "/sandbox.v1.SandboxService/SnapshotPut"
	SandboxService_SnapshotGet_FullMethodName        = "/sandbox.v1.SandboxService/SnapshotGet"
	SandboxService_SnapshotList_FullMethodName       = "/sandbox.v1.SandboxService/SnapshotList"
	SandboxService_GetProcesses_FullMethodName       = "/sandbox.v1.SandboxService/GetProcesses"
	SandboxService_CreateTerminal_FullMethodName     = "/sandbox.v1.SandboxService/CreateTerminal"
	SandboxService_TerminalStream_FullMethodName     = "/sandbox.v1.SandboxService/TerminalStream"
	SandboxService_TerminalWrite_FullMethodName      = "/sandbox.v1.SandboxService/TerminalWrite"
	SandboxService_TerminalResize_FullMethodName     = "/sandbox.v1.SandboxService/TerminalResize"
	SandboxService_TerminalForeground_FullMethodName = "/sandbox.v1.SandboxService/TerminalForeground"
	SandboxService_TerminalSignal_FullMethodName     = "/sandbox.v1.SandboxService/TerminalSignal"
	SandboxService_TerminalDestroy_FullMethodName    = "/sandbox.v1.SandboxService/TerminalDestroy"
	SandboxService_ExposeService_FullMethodName      = "/sandbox.v1.SandboxService/ExposeService"
	SandboxService_UnexposeService_FullMethodName    = "/sandbox.v1.SandboxService/UnexposeService"
	SandboxService_ListExposed_FullMethodName        = "/sandbox.v1.SandboxService/ListExposed"
	SandboxService_UpdateAllowedHosts_FullMethodName = "/sandbox.v1.SandboxService/UpdateAllowedHosts"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	// PauseSession releases the sandbox pod (CPU/memory) while keeping the
	// workspace PVC and session CRD; a paused sandbox resumes via ResumeSession
	// with its filesystem intact (E2B pause semantics, KIP-18).
	PauseSession(ctx context.Context, in *PauseSessionRequest, opts ...grpc.CallOption) (*PauseSessionResponse, error)
	ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*ResumeSessionResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecStreamResponse], error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	PipInstall(ctx context.Context, in *PipInstallRequest, opts ...grpc.CallOption) (*PipInstallResponse, error)
	RunSubAgent(ctx context.Context, in *RunSubAgentRequest, opts ...grpc.CallOption) (*RunSubAgentResponse, error)
	ConfirmAction(ctx context.Context, in *ConfirmActionRequest, opts ...grpc.CallOption) (*ConfirmActionResponse, error)
	ApproveAction(ctx context.Context, in *ApproveActionRequest, opts ...grpc.CallOption) (*ApproveActionResponse, error)
	// Login authenticates the client and returns a signed X.509 certificate for mTLS.
	// First login: pass API key via gRPC metadata (authorization: Bearer <key>).
	// Renewal: present existing valid client cert via mTLS — no API key needed.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// PollRun checks the status of a background execution.
	PollRun(ctx context.Context, in *PollRunRequest, opts ...grpc.CallOption) (*PollRunResponse, error)
	// GetTranscript reads a bounded window of a session's exec transcript
	// (file-backed, offset-resumable; KIP-16 M4 / issue #512).
	GetTranscript(ctx context.Context, in *GetTranscriptRequest, opts ...grpc.CallOption) (*GetTranscriptResponse, error)
	// GetEvents reads the daemon's NDJSON event stream (exec/files/bg events;
	// KIP-16 M5 / issue #513).
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	// Snapshot layer registry (server-side, KIP-16 M2 / issue #511):
	// content-addressed snapshot artifacts hosted by the gateway.
	SnapshotPut(ctx context.Context, in *SnapshotPutRequest, opts ...grpc.CallOption) (*SnapshotPutResponse, error)
	SnapshotGet(ctx context.Context, in *SnapshotGetRequest, opts ...grpc.CallOption) (*SnapshotGetResponse, error)
	SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error)
	// GetProcesses lists processes in the sandbox pod (KIP-16 M5 process topology).
	GetProcesses(ctx context.Context, in *GetProcessesRequest, opts ...grpc.CallOption) (*GetProcessesResponse, error)
	// ── PTY terminal primitive (KIP-19) ───────────────────────────────────────
	// CreateTerminal allocates a PTY and starts argv as a controlling-terminal
	// session leader (argv is NOT shell-interpreted).
	CreateTerminal(ctx context.Context, in *CreateTerminalRequest, opts ...grpc.CallOption) (*CreateTerminalResponse, error)
	// TerminalStream streams terminal output bytes; the final frame carries
	// TerminalExit (exit code / signal) when the top-level process closes.
	TerminalStream(ctx context.Context, in *TerminalStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TerminalStreamResponse], error)
	TerminalWrite(ctx context.Context, in *TerminalWriteRequest, opts ...grpc.CallOption) (*TerminalWriteResponse, error)
	TerminalResize(ctx context.Context, in *TerminalResizeRequest, opts ...grpc.CallOption) (*TerminalResizeResponse, error)
	TerminalForeground(ctx context.Context, in *TerminalForegroundRequest, opts ...grpc.CallOption) (*TerminalForegroundResponse, error)
	TerminalSignal(ctx context.Context, in *TerminalSignalRequest, opts ...grpc.CallOption) (*TerminalSignalResponse, error)
	TerminalDestroy(ctx context.Context, in *TerminalDestroyRequest, opts ...grpc.CallOption) (*TerminalDestroyResponse, error)
	// ── Service exposure (KIP-24) ─────────────────────────────────────────────
	// ExposeService registers an in-sandbox service port for proxying through
	// the k8e API Gateway (Cilium Gateway API :80/:443 -> embedded e2b HTTP
	// server -> reverse proxy to http://<podIP>:<port>; no inbound pod
	// exposure). UnexposeService removes the registration.
	ExposeService(ctx context.Context, in *ExposeServiceRequest, opts ...grpc.CallOption) (*ExposeServiceResponse, error)
	UnexposeService(ctx context.Context, in *UnexposeServiceRequest, opts ...grpc.CallOption) (*UnexposeServiceResponse, error)
	ListExposed(ctx context.Context, in *ListExposedRequest, opts ...grpc.CallOption) (*ListExposedResponse, error)
	// UpdateAllowedHosts replaces the session's egress allowlist and re-applies
	// the per-session CNP so the change is live (FQDN mode) / declared.
	UpdateAllowedHosts(ctx context.Context, in *UpdateAllowedHostsRequest, opts ...grpc.CallOption) (*UpdateAllowedHostsResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, SandboxService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, SandboxService_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) PauseSession(ctx context.Context, in *PauseSessionRequest, opts ...grpc.CallOption) (*PauseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseSessionResponse)
	err := c.cc.Invoke(ctx, SandboxService_PauseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*ResumeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeSessionResponse)
	err := c.cc.Invoke(ctx, SandboxService_ResumeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, SandboxService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[0], SandboxService_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ExecStreamClient = grpc.ServerStreamingClient[ExecStreamResponse]

func (c *sandboxServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SandboxService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SandboxService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) PipInstall(ctx context.Context, in *PipInstallRequest, opts ...grpc.CallOption) (*PipInstallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipInstallResponse)
	err := c.cc.Invoke(ctx, SandboxService_PipInstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) RunSubAgent(ctx context.Context, in *RunSubAgentRequest, opts ...grpc.CallOption) (*RunSubAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSubAgentResponse)
	err := c.cc.Invoke(ctx, SandboxService_RunSubAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ConfirmAction(ctx context.Context, in *ConfirmActionRequest, opts ...grpc.CallOption) (*ConfirmActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmActionResponse)
	err := c.cc.Invoke(ctx, SandboxService_ConfirmAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ApproveAction(ctx context.Context, in *ApproveActionRequest, opts ...grpc.CallOption) (*ApproveActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveActionResponse)
	err := c.cc.Invoke(ctx, SandboxService_ApproveAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, SandboxService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) PollRun(ctx context.Context, in *PollRunRequest, opts ...grpc.CallOption) (*PollRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollRunResponse)
	err := c.cc.Invoke(ctx, SandboxService_PollRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetTranscript(ctx context.Context, in *GetTranscriptRequest, opts ...grpc.CallOption) (*GetTranscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranscriptResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetTranscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SnapshotPut(ctx context.Context, in *SnapshotPutRequest, opts ...grpc.CallOption) (*SnapshotPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotPutResponse)
	err := c.cc.Invoke(ctx, SandboxService_SnapshotPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SnapshotGet(ctx context.Context, in *SnapshotGetRequest, opts ...grpc.CallOption) (*SnapshotGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotGetResponse)
	err := c.cc.Invoke(ctx, SandboxService_SnapshotGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotListResponse)
	err := c.cc.Invoke(ctx, SandboxService_SnapshotList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetProcesses(ctx context.Context, in *GetProcessesRequest, opts ...grpc.CallOption) (*GetProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessesResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CreateTerminal(ctx context.Context, in *CreateTerminalRequest, opts ...grpc.CallOption) (*CreateTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTerminalResponse)
	err := c.cc.Invoke(ctx, SandboxService_CreateTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) TerminalStream(ctx context.Context, in *TerminalStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TerminalStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[1], SandboxService_TerminalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalStreamRequest, TerminalStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_TerminalStreamClient = grpc.ServerStreamingClient[TerminalStreamResponse]

func (c *sandboxServiceClient) TerminalWrite(ctx context.Context, in *TerminalWriteRequest, opts ...grpc.CallOption) (*TerminalWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminalWriteResponse)
	err := c.cc.Invoke(ctx, SandboxService_TerminalWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) TerminalResize(ctx context.Context, in *TerminalResizeRequest, opts ...grpc.CallOption) (*TerminalResizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminalResizeResponse)
	err := c.cc.Invoke(ctx, SandboxService_TerminalResize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) TerminalForeground(ctx context.Context, in *TerminalForegroundRequest, opts ...grpc.CallOption) (*TerminalForegroundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminalForegroundResponse)
	err := c.cc.Invoke(ctx, SandboxService_TerminalForeground_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) TerminalSignal(ctx context.Context, in *TerminalSignalRequest, opts ...grpc.CallOption) (*TerminalSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminalSignalResponse)
	err := c.cc.Invoke(ctx, SandboxService_TerminalSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) TerminalDestroy(ctx context.Context, in *TerminalDestroyRequest, opts ...grpc.CallOption) (*TerminalDestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminalDestroyResponse)
	err := c.cc.Invoke(ctx, SandboxService_TerminalDestroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ExposeService(ctx context.Context, in *ExposeServiceRequest, opts ...grpc.CallOption) (*ExposeServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExposeServiceResponse)
	err := c.cc.Invoke(ctx, SandboxService_ExposeService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) UnexposeService(ctx context.Context, in *UnexposeServiceRequest, opts ...grpc.CallOption) (*UnexposeServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnexposeServiceResponse)
	err := c.cc.Invoke(ctx, SandboxService_UnexposeService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListExposed(ctx context.Context, in *ListExposedRequest, opts ...grpc.CallOption) (*ListExposedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExposedResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListExposed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) UpdateAllowedHosts(ctx context.Context, in *UpdateAllowedHostsRequest, opts ...grpc.CallOption) (*UpdateAllowedHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAllowedHostsResponse)
	err := c.cc.Invoke(ctx, SandboxService_UpdateAllowedHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
type SandboxServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	// PauseSession releases the sandbox pod (CPU/memory) while keeping the
	// workspace PVC and session CRD; a paused sandbox resumes via ResumeSession
	// with its filesystem intact (E2B pause semantics, KIP-18).
	PauseSession(context.Context, *PauseSessionRequest) (*PauseSessionResponse, error)
	ResumeSession(context.Context, *ResumeSessionRequest) (*ResumeSessionResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecStreamResponse]) error
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	PipInstall(context.Context, *PipInstallRequest) (*PipInstallResponse, error)
	RunSubAgent(context.Context, *RunSubAgentRequest) (*RunSubAgentResponse, error)
	ConfirmAction(context.Context, *ConfirmActionRequest) (*ConfirmActionResponse, error)
	ApproveAction(context.Context, *ApproveActionRequest) (*ApproveActionResponse, error)
	// Login authenticates the client and returns a signed X.509 certificate for mTLS.
	// First login: pass API key via gRPC metadata (authorization: Bearer <key>).
	// Renewal: present existing valid client cert via mTLS — no API key needed.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// PollRun checks the status of a background execution.
	PollRun(context.Context, *PollRunRequest) (*PollRunResponse, error)
	// GetTranscript reads a bounded window of a session's exec transcript
	// (file-backed, offset-resumable; KIP-16 M4 / issue #512).
	GetTranscript(context.Context, *GetTranscriptRequest) (*GetTranscriptResponse, error)
	// GetEvents reads the daemon's NDJSON event stream (exec/files/bg events;
	// KIP-16 M5 / issue #513).
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	// Snapshot layer registry (server-side, KIP-16 M2 / issue #511):
	// content-addressed snapshot artifacts hosted by the gateway.
	SnapshotPut(context.Context, *SnapshotPutRequest) (*SnapshotPutResponse, error)
	SnapshotGet(context.Context, *SnapshotGetRequest) (*SnapshotGetResponse, error)
	SnapshotList(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error)
	// GetProcesses lists processes in the sandbox pod (KIP-16 M5 process topology).
	GetProcesses(context.Context, *GetProcessesRequest) (*GetProcessesResponse, error)
	// ── PTY terminal primitive (KIP-19) ───────────────────────────────────────
	// CreateTerminal allocates a PTY and starts argv as a controlling-terminal
	// session leader (argv is NOT shell-interpreted).
	CreateTerminal(context.Context, *CreateTerminalRequest) (*CreateTerminalResponse, error)
	// TerminalStream streams terminal output bytes; the final frame carries
	// TerminalExit (exit code / signal) when the top-level process closes.
	TerminalStream(*TerminalStreamRequest, grpc.ServerStreamingServer[TerminalStreamResponse]) error
	TerminalWrite(context.Context, *TerminalWriteRequest) (*TerminalWriteResponse, error)
	TerminalResize(context.Context, *TerminalResizeRequest) (*TerminalResizeResponse, error)
	TerminalForeground(context.Context, *TerminalForegroundRequest) (*TerminalForegroundResponse, error)
	TerminalSignal(context.Context, *TerminalSignalRequest) (*TerminalSignalResponse, error)
	TerminalDestroy(context.Context, *TerminalDestroyRequest) (*TerminalDestroyResponse, error)
	// ── Service exposure (KIP-24) ─────────────────────────────────────────────
	// ExposeService registers an in-sandbox service port for proxying through
	// the k8e API Gateway (Cilium Gateway API :80/:443 -> embedded e2b HTTP
	// server -> reverse proxy to http://<podIP>:<port>; no inbound pod
	// exposure). UnexposeService removes the registration.
	ExposeService(context.Context, *ExposeServiceRequest) (*ExposeServiceResponse, error)
	UnexposeService(context.Context, *UnexposeServiceRequest) (*UnexposeServiceResponse, error)
	ListExposed(context.Context, *ListExposedRequest) (*ListExposedResponse, error)
	// UpdateAllowedHosts replaces the session's egress allowlist and re-applies
	// the per-session CNP so the change is live (FQDN mode) / declared.
	UpdateAllowedHosts(context.Context, *UpdateAllowedHostsRequest) (*UpdateAllowedHostsResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSandboxServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSandboxServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSandboxServiceServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedSandboxServiceServer) PauseSession(context.Context, *PauseSessionRequest) (*PauseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseSession not implemented")
}
func (UnimplementedSandboxServiceServer) ResumeSession(context.Context, *ResumeSessionRequest) (*ResumeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSession not implemented")
}
func (UnimplementedSandboxServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxServiceServer) ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedSandboxServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedSandboxServiceServer) PipInstall(context.Context, *PipInstallRequest) (*PipInstallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PipInstall not implemented")
}
func (UnimplementedSandboxServiceServer) RunSubAgent(context.Context, *RunSubAgentRequest) (*RunSubAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSubAgent not implemented")
}
func (UnimplementedSandboxServiceServer) ConfirmAction(context.Context, *ConfirmActionRequest) (*ConfirmActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmAction not implemented")
}
func (UnimplementedSandboxServiceServer) ApproveAction(context.Context, *ApproveActionRequest) (*ApproveActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveAction not implemented")
}
func (UnimplementedSandboxServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSandboxServiceServer) PollRun(context.Context, *PollRunRequest) (*PollRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollRun not implemented")
}
func (UnimplementedSandboxServiceServer) GetTranscript(context.Context, *GetTranscriptRequest) (*GetTranscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTranscript not implemented")
}
func (UnimplementedSandboxServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedSandboxServiceServer) SnapshotPut(context.Context, *SnapshotPutRequest) (*SnapshotPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotPut not implemented")
}
func (UnimplementedSandboxServiceServer) SnapshotGet(context.Context, *SnapshotGetRequest) (*SnapshotGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotGet not implemented")
}
func (UnimplementedSandboxServiceServer) SnapshotList(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotList not implemented")
}
func (UnimplementedSandboxServiceServer) GetProcesses(context.Context, *GetProcessesRequest) (*GetProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcesses not implemented")
}
func (UnimplementedSandboxServiceServer) CreateTerminal(context.Context, *CreateTerminalRequest) (*CreateTerminalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTerminal not implemented")
}
func (UnimplementedSandboxServiceServer) TerminalStream(*TerminalStreamRequest, grpc.ServerStreamingServer[TerminalStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method TerminalStream not implemented")
}
func (UnimplementedSandboxServiceServer) TerminalWrite(context.Context, *TerminalWriteRequest) (*TerminalWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminalWrite not implemented")
}
func (UnimplementedSandboxServiceServer) TerminalResize(context.Context, *TerminalResizeRequest) (*TerminalResizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminalResize not implemented")
}
func (UnimplementedSandboxServiceServer) TerminalForeground(context.Context, *TerminalForegroundRequest) (*TerminalForegroundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminalForeground not implemented")
}
func (UnimplementedSandboxServiceServer) TerminalSignal(context.Context, *TerminalSignalRequest) (*TerminalSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminalSignal not implemented")
}
func (UnimplementedSandboxServiceServer) TerminalDestroy(context.Context, *TerminalDestroyRequest) (*TerminalDestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminalDestroy not implemented")
}
func (UnimplementedSandboxServiceServer) ExposeService(context.Context, *ExposeServiceRequest) (*ExposeServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExposeService not implemented")
}
func (UnimplementedSandboxServiceServer) UnexposeService(context.Context, *UnexposeServiceRequest) (*UnexposeServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnexposeService not implemented")
}
func (UnimplementedSandboxServiceServer) ListExposed(context.Context, *ListExposedRequest) (*ListExposedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExposed not implemented")
}
func (UnimplementedSandboxServiceServer) UpdateAllowedHosts(context.Context, *UpdateAllowedHostsRequest) (*UpdateAllowedHostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAllowedHosts not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_PauseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).PauseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_PauseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).PauseSession(ctx, req.(*PauseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ResumeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ResumeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ResumeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ResumeSession(ctx, req.(*ResumeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).ExecStream(m, &grpc.GenericServerStream[ExecRequest, ExecStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ExecStreamServer = grpc.ServerStreamingServer[ExecStreamResponse]

func _SandboxService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_PipInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).PipInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_PipInstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).PipInstall(ctx, req.(*PipInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_RunSubAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSubAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).RunSubAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_RunSubAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).RunSubAgent(ctx, req.(*RunSubAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ConfirmAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ConfirmAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ConfirmAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ConfirmAction(ctx, req.(*ConfirmActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ApproveAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ApproveAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ApproveAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ApproveAction(ctx, req.(*ApproveActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_PollRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).PollRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_PollRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).PollRun(ctx, req.(*PollRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetTranscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetTranscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetTranscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetTranscript(ctx, req.(*GetTranscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SnapshotPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SnapshotPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SnapshotPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SnapshotPut(ctx, req.(*SnapshotPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SnapshotGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SnapshotGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SnapshotGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SnapshotGet(ctx, req.(*SnapshotGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SnapshotList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SnapshotList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SnapshotList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SnapshotList(ctx, req.(*SnapshotListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetProcesses(ctx, req.(*GetProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CreateTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateTerminal(ctx, req.(*CreateTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_TerminalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TerminalStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).TerminalStream(m, &grpc.GenericServerStream[TerminalStreamRequest, TerminalStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_TerminalStreamServer = grpc.ServerStreamingServer[TerminalStreamResponse]

func _SandboxService_TerminalWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).TerminalWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_TerminalWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).TerminalWrite(ctx, req.(*TerminalWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_TerminalResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).TerminalResize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_TerminalResize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).TerminalResize(ctx, req.(*TerminalResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_TerminalForeground_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalForegroundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).TerminalForeground(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_TerminalForeground_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).TerminalForeground(ctx, req.(*TerminalForegroundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_TerminalSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).TerminalSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_TerminalSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).TerminalSignal(ctx, req.(*TerminalSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_TerminalDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).TerminalDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_TerminalDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).TerminalDestroy(ctx, req.(*TerminalDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ExposeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ExposeService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ExposeService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ExposeService(ctx, req.(*ExposeServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_UnexposeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnexposeServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).UnexposeService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_UnexposeService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).UnexposeService(ctx, req.(*UnexposeServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListExposed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExposedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListExposed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListExposed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListExposed(ctx, req.(*ListExposedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_UpdateAllowedHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAllowedHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).UpdateAllowedHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_UpdateAllowedHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).UpdateAllowedHosts(ctx, req.(*UpdateAllowedHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SandboxService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SandboxService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _SandboxService_ListSessions_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _SandboxService_DestroySession_Handler,
		},
		{
			MethodName: "PauseSession",
			Handler:    _SandboxService_PauseSession_Handler,
		},
		{
			MethodName: "ResumeSession",
			Handler:    _SandboxService_ResumeSession_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _SandboxService_Exec_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SandboxService_WriteFile_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SandboxService_ReadFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _SandboxService_ListFiles_Handler,
		},
		{
			MethodName: "PipInstall",
			Handler:    _SandboxService_PipInstall_Handler,
		},
		{
			MethodName: "RunSubAgent",
			Handler:    _SandboxService_RunSubAgent_Handler,
		},
		{
			MethodName: "ConfirmAction",
			Handler:    _SandboxService_ConfirmAction_Handler,
		},
		{
			MethodName: "ApproveAction",
			Handler:    _SandboxService_ApproveAction_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _SandboxService_Login_Handler,
		},
		{
			MethodName: "PollRun",
			Handler:    _SandboxService_PollRun_Handler,
		},
		{
			MethodName: "GetTranscript",
			Handler:    _SandboxService_GetTranscript_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _SandboxService_GetEvents_Handler,
		},
		{
			MethodName: "SnapshotPut",
			Handler:    _SandboxService_SnapshotPut_Handler,
		},
		{
			MethodName: "SnapshotGet",
			Handler:    _SandboxService_SnapshotGet_Handler,
		},
		{
			MethodName: "SnapshotList",
			Handler:    _SandboxService_SnapshotList_Handler,
		},
		{
			MethodName: "GetProcesses",
			Handler:    _SandboxService_GetProcesses_Handler,
		},
		{
			MethodName: "CreateTerminal",
			Handler:    _SandboxService_CreateTerminal_Handler,
		},
		{
			MethodName: "TerminalWrite",
			Handler:    _SandboxService_TerminalWrite_Handler,
		},
		{
			MethodName: "TerminalResize",
			Handler:    _SandboxService_TerminalResize_Handler,
		},
		{
			MethodName: "TerminalForeground",
			Handler:    _SandboxService_TerminalForeground_Handler,
		},
		{
			MethodName: "TerminalSignal",
			Handler:    _SandboxService_TerminalSignal_Handler,
		},
		{
			MethodName: "TerminalDestroy",
			Handler:    _SandboxService_TerminalDestroy_Handler,
		},
		{
			MethodName: "ExposeService",
			Handler:    _SandboxService_ExposeService_Handler,
		},
		{
			MethodName: "UnexposeService",
			Handler:    _SandboxService_UnexposeService_Handler,
		},
		{
			MethodName: "ListExposed",
			Handler:    _SandboxService_ListExposed_Handler,
		},
		{
			MethodName: "UpdateAllowedHosts",
			Handler:    _SandboxService_UpdateAllowedHosts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _SandboxService_ExecStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TerminalStream",
			Handler:       _SandboxService_TerminalStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sandbox/v1/sandbox.proto",
}
