package sandboxcli

import (
	"regexp"
	"testing"
)

var hex64 = regexp.MustCompile(`^[0-9a-f]{64}$`)

// TestGenerateAPIKeyHexOnly guards the e2b SDK compatibility contract: keys
// generated by `k8e sandbox-apikey create` must be bare hex (no "k8e-"
// prefix) so a single key works for the gateway Secret, the e2b server's
// --apikey, and official e2b SDK clients ("e2b_" + key — the SDK validates
// /^e2b_[0-9a-f]+$/ client-side before any request).
func TestGenerateAPIKeyHexOnly(t *testing.T) {
	seen := map[string]bool{}
	for i := 0; i < 10; i++ {
		key := generateAPIKey()
		if !hex64.MatchString(key) {
			t.Fatalf("generateAPIKey() = %q, want 64 lowercase hex chars (e2b SDK compatible)", key)
		}
		if seen[key] {
			t.Fatalf("generateAPIKey() returned duplicate key %q", key)
		}
		seen[key] = true
	}
}

func TestGenerateAPIKeySDKForm(t *testing.T) {
	sdk := regexp.MustCompile(`^e2b_[0-9a-f]{64}$`)
	key := generateAPIKey()
	if got := "e2b_" + key; !sdk.MatchString(got) {
		t.Fatalf("official SDK apiKey form %q does not match /^e2b_[0-9a-f]{64}$/", got)
	}
}
