// Package grpc contains hand-written gRPC service types aligned with sandbox.proto.
// These replace protobuf-generated code to avoid requiring protoc in the build.
package grpc

import (
	"context"

	"google.golang.org/grpc"
)

// --- Request / Response types ---

type CreateSessionRequest struct {
	SessionId    string   `json:"session_id"`
	TenantId     string   `json:"tenant_id"`
	AllowedHosts []string `json:"allowed_hosts"`
	RuntimeClass string   `json:"runtime_class"`
}
type CreateSessionResponse struct {
	SessionId string `json:"session_id"`
	PodIp     string `json:"pod_ip"`
}

type DestroySessionRequest  struct{ SessionId string }
type DestroySessionResponse struct{ Ok bool }

type ExecRequest struct {
	SessionId string `json:"session_id"`
	Command   string `json:"command"`
	Timeout   int32  `json:"timeout"`
	Workdir   string `json:"workdir"`
}
type ExecResponse struct {
	Stdout   string `json:"stdout"`
	Stderr   string `json:"stderr"`
	ExitCode int32  `json:"exit_code"`
}
type ExecStreamResponse struct{ Chunk string }

type WriteFileRequest struct {
	SessionId string
	Path      string
	Content   string
	Mode      string
}
type WriteFileResponse struct{ Ok bool }

type ReadFileRequest  struct{ SessionId, Path string }
type ReadFileResponse struct{ Content string }

type ListFilesRequest  struct{ SessionId string; Since int64 }
type ListFilesResponse struct{ Files []*FileEntry }
type FileEntry         struct{ Path string; Modified int64 }

type PipInstallRequest  struct{ SessionId string; Packages []string }
type PipInstallResponse struct{ Output string; ExitCode int32 }

type RunSubAgentRequest struct {
	ParentSessionId string
	AgentType       string
	WorkspacePath   string
}
type RunSubAgentResponse struct{ SessionId string }

type ConfirmActionRequest struct {
	SessionId  string
	Action     string
	ApprovalId string
}
type ConfirmActionResponse struct {
	ApprovalId string
	Approved   bool
}

// --- Service interface ---

type SandboxServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	ExecStream(*ExecRequest, SandboxService_ExecStreamServer) error
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	PipInstall(context.Context, *PipInstallRequest) (*PipInstallResponse, error)
	RunSubAgent(context.Context, *RunSubAgentRequest) (*RunSubAgentResponse, error)
	ConfirmAction(context.Context, *ConfirmActionRequest) (*ConfirmActionResponse, error)
}

type SandboxService_ExecStreamServer interface {
	Send(*ExecStreamResponse) error
	Context() context.Context
	grpc.ServerStream
}

// RegisterSandboxServiceServer registers the service with a gRPC server.
// Full gRPC method routing would be generated by protoc; this stub satisfies compilation.
func RegisterSandboxServiceServer(s *grpc.Server, srv SandboxServiceServer) {
	// Registration is a no-op until protoc-generated code is added.
	// The server is functional via direct HTTP routing in Start().
	_ = s
	_ = srv
}
